# Generated by Django 2.2.1 on 2019-07-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='src/static/images/')),
                ('title', models.CharField(max_length=26)),
                ('content', models.TextField()),
            ],
        ),
    ]
