# Generated by Django 2.2.1 on 2019-07-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
