# Generated by Django 2.2.1 on 2019-07-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databse', '0002_auto_20190725_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
